### ISSUE TITLE
Duplicate invalid connection ID

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-common#9]
Tests are now failing because invalid connection ID is now 80018 instead of the old https://github.com/ably/ably-common/blob/master/protocol/errors.json#L12.  Why is there a duplicate and why did this change?

**Comment by paddybyers** [comment]
Here's the commit where it changed:

https://github.com/ably/realtime/commit/1f0aca13164e258e944662351c5fda289764f36a

It was changed because an ably-java test was expecting that code and had started failing. When the `connectionKey` format changed it meant that unknown connectionKeys, and invalidly formed connecitionKeys, were detected in different places and so there were differences in the errors returned.

There are two distinct errors now for bad `connectionIds`: 

- 80018: an invalidly formed `connectionId` - ie the `connectionId` was never valid;
- 80008: `connectionId` not found - eg a recovery attempt after the connection is dead.

**Comment by mattheworiordan** [comment]
Ok, thanks for clarifying
